### ISSUE TITLE
[bug]: Incorrect LinkedIn Profile Link on Portfolio

### ISSUE THREAD

**Issue by tarunkumarkale** [Shyam-Raghuwanshi/shyam-portfolio#1]
Description:
When I click on the LinkedIn profile logo on your portfolio website, it redirects me to your Instagram profile instead of your LinkedIn profile. This seems to be a misconfiguration or a hyperlink error.

Steps to Reproduce:

Go to [Portfolio Website URL].
Look for the LinkedIn logo or link.
Click on the LinkedIn logo or link.
Expected Behavior:
Clicking on the LinkedIn logo or link should redirect users to your LinkedIn profile.

Actual Behavior:
Clicking on the LinkedIn logo or link redirects users to your Instagram profile.

Screenshot 
![Screenshot 2024-02-26 144641](https://github.com/Shyam-Raghuwanshi/shyam-portfolio/assets/130459422/9c230202-bc60-4ecc-915d-7e1eb37d37aa)

**Comment by Shyam-Raghuwanshi** [comment]
Thanks brother ❣️ i will fix this
